**捕获异常try-except**  
```python
In [1]: def div(a, b):
   ...:     return a / b
   ...: 

In [2]: div(1, 0)
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-2-4267cdef819f> in <module>()
----> 1 div(1, 0)

<ipython-input-1-6ba1042d1130> in div(a, b)
      1 def div(a, b):
----> 2     return a / b

ZeroDivisionError: division by zero
```
```python
In [3]: try:
   ...:     div(1, 0)
   ...: except ZeroDivisionError:
   ...:     print('Oops!')
   ...:     
Oops!
```
组合try语法：
```python
In [5]: def div(a, b):
   ...:     try:
   ...:         result = a / b
   ...:     except ZeroDivisionError as e:
   ...:         print(e)
   ...:     else:
   ...:         print('result = ',result)
   ...:     finally:
   ...:         print('executing finally clause')
   ...:       

In [6]: div(1, 2)
result =  0.5
executing finally clause

In [7]: div(1, 0)
division by zero
executing finally clause
```
